### ISSUE TITLE
Should we simply allow duplicate cases?

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#10]
The main reason why we disallow duplicate cases and have a rule that says no two cases may operate on the same end of the same channel is that otherwise `Select` couldn't detect where a new iteration of the loop starts.

For example, the following code doesn't work because `Select` will assume that there is only one case in the loop and then go off the rails:

```rust
let mut sel = Select::new();
loop {
    if let Ok(_) = sel.recv(&rx) { println!("First!"); break; }
    if let Ok(_) = sel.recv(&rx) { println!("First!"); break; }
    if let Ok(_) = sel.recv(&rx2) { println!("Second!"); break; }
}
```

However, if we require that each iteration of the loop has to start with `sel.step()`, the problem goes away and `Select` can understand the same arrangement just fine:

```rust
let mut sel = Select::new();
loop {
    sel.step();
    if let Ok(_) = sel.recv(&rx) { println!("First!"); break; }
    if let Ok(_) = sel.recv(&rx) { println!("First!"); break; }
    if let Ok(_) = sel.recv(&rx2) { println!("Second!"); break; }
}
```

Requiring `sel.step()` at the beginning of the loop is surely a small unergonomic bump, but at the same time one of the subtler rules around selection simply goes away. Perhaps this is a net win?

cc @TimNN

**Comment by droundy** [comment]
Particularly with the macro available, this sounds to me like a net win.
