### ISSUE TITLE
Behavior of send(..) in select

### ISSUE THREAD

**Issue by arthurprs** [crossbeam-rs/crossbeam-channel#107]
Consider this snippet

```
select! {
  send(Chan, Msg) =>
  other.... =>
}
```

If the program go into the other branch are you guaranteed that Msg didn't make into Chan and will get dropped? Also, is it possible to recover Msg?

**Comment by stjepang** [comment]
> If the program go into the other branch are you guaranteed that Msg didn't make into Chan and will get dropped?

Yes and no:

* Yes, `Msg` will not be sent into `Chan`.
* No, `Msg` will not be dropped.

> Also, is it possible to recover Msg?

No need to recover because `Msg` will be left intact. :)

**Comment by arthurprs** [comment]
Aha! Thanks!
