### ISSUE TITLE
Simplified send in selection

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#11]
The trickiest thing about send operations in selection is that we have to give ownership of the message to each call to `send`, and then regain ownership if sending fails. This also means that the message has to be bound to a mutable variable and in `select_loop!` we have to use something like `send(tx, mut msg)`.

I've just realized that in all three underlying channel implementations (list-based, array-based, and exchanger-based flavor) we send messages in two steps: first we acquire a slot in the queue, and on success we finally supply the message.

Here's an example for illustration. Currently, we send messages in select like this:

```rust
let mut msg = "foo".to_string();
let mut sel = Select::new();
loop {
    if let Err(err) = sel.send(&tx, msg) {
        msg = err.0;
    } else {
        break;
    }
}
```

But with an explicit two-step approach instead of ownership juggling we could have:

```rust
let msg = "foo".to_string();
let mut sel = Select::new();
loop {
    if let Ok(s) = sel.send(&tx) {
        s.finish(msg);
        break;
    }
}
```

This is very similar to the upcoming placement-new syntax.

Note that this would remove one more roadbump from `select_loop!` - if you write `send(tx, msg)`, then `msg` will be evaluated at most once rather than in every iteration of the loop.

cc @TimNN

**Comment by droundy** [comment]
This sounds great, and seems similar to my peek Receiver idea #12.  It could be nice to add an API for this for ordinary non select users.

**Comment by glaebhoerl** [comment]
(Usual question: what happens in case of `mem::forget(s)`? Or if a panic happens while `s` is live? These are the kind of things that make placement-new difficult, at least.)

**Comment by stjepang** [comment]
@glaebhoerl A deadlock. Some other send/recv operations on the same channel will block forever.

Now that you mention it, I'm curious: how is placement-new going to handle `mem::forget` and panics?

**Comment by glaebhoerl** [comment]
I don't usually manage to understand it for long enough to remember it later. In the case of panics I think it has a destructor which undoes the placement-reservation? Not sure about `forget`.

**Comment by ArtemGr** [comment]
> Or if a panic happens while s is live?

Panic unwinds the stack, calls `drop` on `s`, everything's fine.

**Comment by stjepang** [comment]
> Panic unwinds the stack, calls `drop` on `s`, everything's fine.

Unfortunately, it is not possible to release the acquired slot in the channel when dropping `s`. 

Suppose that you have a bounded channel, which is represented as a fixed array of N slots for messages. Even after you reserve a slot by calling `sel.send(&tx)` (or something similar), other send operations may proceed.

If you want to release the slot without supplying a message, that slot will become a hole in the array, which will break a lot of channel invariants. If we allow holes, then we cannot compute the length of the channel as `tail.wrapping_sub(head) % capacity` - we have to account for potential holes between the head and the tail as well.

**Comment by ArtemGr** [comment]
I totally get it, but then the API is unsafe by design, you can break it any time, panics or no panics.

**Comment by stjepang** [comment]
Well, it's not unsafe (cannot cause undefined behavior or memory unsafety), but it can cause deadlocks. :)

If you simply leave a reserved slot without supplying a message, then a receive operation attempting to take the message from that slot will simply wait until it is ready. Note that each slot has an atomic *ready* flag in some form - and a receive operation will always wait until the flag is set to `true`.

**Comment by ArtemGr** [comment]
Copy.

**Comment by ArtemGr** [comment]
> If you simply leave a reserved slot without supplying a message, then a receive operation attempting to take the message from that slot will simply wait until it is ready.

To make it less dangerous, I'd probably only allow the "placement send" with a default-generating functor.

```
let msg = "foo".to_string();
let mut sel = Select::new();
loop {
    if let Ok(s) = sel.send(&tx, || String::new()) {
        s.finish(msg);
        break;
    }
}
```

If the call site thinks that it won't leave the slot unattended, it can assert this with panic:
```
    if let Ok(s) = sel.send(&tx, || panic!()) {
```
