### ISSUE TITLE
Duplicate crossbeam-utils dependency

### ISSUE THREAD

**Issue by Bathtor** [crossbeam-rs/crossbeam-channel#18]
I noticed that crossbeam-channel 0.1.1 seems to pull in crossbeam-utils twice: v0.1.0 (directly) and v0.2.1 (via crossbeam-epoch).

I'm kind of new to the rust/cargo ecosystem, so I'm not sure if this is a practical issue in terms if linking ambiguity, but coming from the maven ecosystem, it always make nervous to see duplicate dependencies with different versions.

**Comment by Bathtor** [comment]
Oh, I just saw, there's already a pull request on this. Nevermind then.
Though, I would still be curious if this is actually a practical issue.

**Comment by stjepang** [comment]
Hi @Bathtor, and sorry for the late reply! Rust/Cargo can handle multiple versions of the same crate pretty seamlessly. I'm not familiar with Maven so cannot make a direct comparison, but I can explain how it works in Rust.

Suppose that you depend (either directly or transitively) on versions 0.1.0 and 0.2.1 of `crossbeam-utils`. Both versions will get linked into your crate/program, but note that different versions of `crossbeam-utils` behave as completely separate crates - their types cannot be interchanged. E.g. you cannot use the struct `CachePadded` from version 0.1.0 and send a value of that type into a function expecting a `CachePadded` from version 0.2.1 - the types may have the same name, but are actually completely different.

Generally speaking, using multiple versions of the same crate is no problem. However, multiple versions are a serious concern for very popular crates whose types are intended to be pervasively used across the whole ecosystem. Off the top of my head, examples of such crates would be `serde` and `futures`.

Further reading:

* [`http`](https://docs.rs/http) - a crate that only exposes a standard set of types intended to be used by all the other HTTP-related crates across the ecosystem. This crate should only publish new versions by bumping the minor semver number.

* [`semver-trick`](https://github.com/dtolnay/semver-trick) - an interesting trick that allows you to export the same type throughout multiple versions of your crate. In other words, this trick would allow you to make `CachePadded` in versions 0.1.0 and 0.2.1 really be the same type! The basic idea is that version 0.1.0 depends on 0.2.1 (yeah, depends on the same crate :)), but simply re-exports the type from 0.2.1 as if it were its own (using `pub use crossbeam_utils_0_2_1::CachePadded` or something similar).

**Comment by Bathtor** [comment]
Cool, thank you so much for the very detailed answer!
