### ISSUE TITLE
Oneshot channel

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#25]
We might want to introduce a new type of channel in addition to bounded and unbounded channels:

```rust
fn oneshot<T>() -> (Sender<T>, Receiver<T>);
```

This type of channel internally has only one slot and gets automatically disconnected as soon as one message is sent into it. That means it uses less memory and is faster than unbounded and bounded channels. Another advantage might be that it makes code more robust: if you really need to use the channel only once, then automatic disconnection might prevent bugs or help in debugging.

The main drawback is that automatic disconnection makes `oneshot` kind of odd in comparison to other channel types. However, we already have zero-capacity channels, which I find to be even more odd, so perhaps introducing `oneshot` is not a big deal.

cc @dbrgn

**Comment by ArtemGr** [comment]
Something I've just came up with for my own use: http://play.integer32.com/?gist=7deb47675fb42b43bfc6b9dfc6908f97&version=stable.
I wonder if it'll be of some help here?

**Comment by stjepang** [comment]
@ArtemGr That looks a lot like what I had in mind.

A question for you: why use your own `oneshot` channel instead of `crossbeam-channel` or `mpsc`? Is it performance, convenience, or perhaps something else? Is it simply because of unwind safety?

I'm asking to gather compelling motivation for adding the oneshot variant to `crossbeam-channel`. Basically, someone just has to say "I need this feature for this or that reason".

**Comment by ArtemGr** [comment]
> Is it simply because of unwind safety?

It is!

I have a loop that runs functions passed to it. That loop is rather important and shouldn't die if a stray function decided to panic. Thus the functions passed into the loop need to cross the catch_unwind barrier and be unwind-safe. But at the same time I'd like to be able to get something back from the functions in a convenient manner.

If you're curious, I'm prototyping a replicated SQLite system.
```
  /// Schedule the callback to be executed inside the write thread.  
  /// The callback will run inside a batching transaction.  
  /// Database modifications will be saved with a session and forwarded to the peer replica.  
  /// Might return an error if the write queue is full.
  ///
  /// The callback should be limited to modifying the database, it should not be doing something else on the writer thread.
  ///
  /// The callback should not affect the batching transaction (it should not be calling BEGIN, COMMIT or ROLLBACK)
  /// but it can use the "https://www.sqlite.org/lang_savepoint.html" nested transactions.
  ///
  /// Example of waiting for callback results:
  ///
  ///     let (tx, rx) = oneshot::oneshot();
  ///     try_s! (sqlite.write (move |db| tx.send (db.exec ("CREATE TABLE IF NOT EXISTS test (i INTEGER PRIMARY KEY NOT NULL) WITHOUT ROWID"))));
  ///     try_s! (try_s! (rx.recv()));
  pub fn write<F> (&self, cb: F) -> Result<(), String> where F: 'static + FnOnce (&SQLiteHandle) + Send + UnwindSafe {
    let write_op = WriteOp {cb: Box::new (cb)};
    try_s! (self.writer_tx.try_send (write_op));
    Ok(())}

  /// Schedule the callback to be executed inside the write thread.  
  /// Then wait for it to run.
  ///
  ///     try_s! (sqlite.write_and_wait (|db| db.exec ("INSERT INTO test (i) VALUES (123)")));
  pub fn write_and_wait<F> (&self, cb: F) -> Result<(), String> where F: 'static + FnOnce (&SQLiteHandle) -> Result<(), String> + Send + UnwindSafe {
    let (tx, rx) = oneshot::oneshot();
    try_s! (self.write (move |db| tx.send (cb (db))));
    try_s! (try_s! (rx.recv()));
    Ok(())}}
```
