### ISSUE TITLE
Introduce polling and remove `Select`

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#26]
Here's an idea.

Right now, we have a quite complex `Select` mechanism, but it will barely be used at all. The reason is that `select_loop!` is already powerful enough for the vast majority of use cases. That means `Select` will be used in very niche situations only, like the one in `ipc-channel` (see issue #6).

Also, `ipc-channel` needs a feature we currently don't have: stopping selection as soon as any channel becomes disconnected (issue #6). This is again a very niche feature and shoehorning it into `Select` feels like a hack, which got me thinking about all this.

Moreover, we're going to add support for futures (#22). Selection and blocking is already very reminiscent of futures, but I believe we could take a step further and make it even more so.

I propose introducing two new methods: `Sender::poll_send` and `Receiver::poll_recv`. These methods should be identical to `Sender::try_send` and `Receiver::try_recv`, with one important difference: if they fail (due to the channel being full/empty), the current thread (`std::thread::Thread`) is added to an internal wait list and unparked by another operation as soon as the send/recv operation can proceed or the channel becomes disconnected.

This is the same idea as the one behind `Future::poll`. Put differently, `poll_send` and `poll_recv` are similar to `Sink::start_send` and `Stream::poll`, except they work with *threads* rather than *tasks*. And there is something about channels working with both *threads* and *tasks* more-or-less the same way that feels right.

Note that these polling methods are very powerful - in fact, they allow us to roll our own `Select`. `Select` is essentially just a series of `try_send`/`try_recv` calls followed by another series of `poll_send`/`poll_recv` calls, followed by `thread::park()`.

If we introduce `poll_send`/`poll_recv`, that'll cover the requirements of `ipc-channel` - it won't have to use `Select` at all! And the whole problem with `any_selected` becomes irrelevant so we can forget about it. Since polling is even more powerful that present `Select`, I suggest we just get rid of it forever. It's a very complex piece of code, rarely used, and apparently not good enough even in those rare cases. So why even bother with it?

One potential problem with polling is that, if we call `poll_send`/`poll_recv` too often, threads might get spuriously unparked up very often. For example, if we roll our own selection and call `poll_recv` on a lot of channels, then the current thread might get spuriously unparked a lot of times even after selection ends. That is a potential waste of CPU time, but maybe not a big concern - I'm not sure. It's possible to remedy the problem by introducing function `cancel_polls()` that cancels all currently registered wakeups associated with the current thread.

cc @SimonSapin @TimNN @alexcrichton - you might be interested.

**Comment by birkenfeld** [comment]
I have a use case which currently uses `Select`: a list of channels contained in a vector of "Connection" structs which I want to select over. In general, it seems to me that a dynamic list of channels to be selected over is something that will crop up a lot in real world code (as opposed to examples).

Would this become more cumbersome with the proposed API?

**Comment by stjepang** [comment]
The current `Select` API is quite restrictive - it basically says: "You must follow these rules, or else weird deadlocks will be your fault." It also runs a complicated state machine behind the curtains. Understanding how it works and why it was designed the way it is is far from straightforward.

My proposal is to simplify the interface for dynamic selection by taking inspiration from the `Future` trait. Calling `.poll()` on a `Future` means asking "Hey, give me the result if it's ready. If not, please wake me up (unpark me) when it becomes ready."

We could add method `poll_recv` to `Receiver` that works very similarly, i.e. "Receive an element from the channel if there is one. If not, please unpark this thread when there will be one."

Here's an example. Currently, dynamic selection works like this:

```rust
let mut sel = Select::new();
let msg = 'select: loop {
    for r in &receivers {
        if let Some(msg) = sel.recv(r) {
            break 'select msg;
        }
    }
};
```

Under the new proposal, it might look like this:

```rust
// Note: Selection is not fair anymore. If you want fairness, implement it yourself. :)
// Pro-tip: Randomly shuffle the receiver list.
let msg = 'select: loop {
    for r in &receivers {
        if let Ok(msg) = r.poll_recv() {
            break 'select msg;
        }
    }
    std::thread::park();
};

// We're done selecting.
// Some of the calls to `poll_recv` might wake us up in the future, but we don't care anymore.
// Cancel those polls to avoid spurious wakeups.
for r in &receivers {
    r.poll_cancel();
}
```

@alexcrichton Quick question: Do you think it's necessary to cancel the calls to `poll` at the end of selection in order to avoid spurious wakeups? I'm not sure, but the simplification around `Future::poll` and `Future::schedule` seems related to my qeustion, so perhaps you might have some insight into this?

**Comment by SimonSapin** [comment]
I don’t know what thread parking means. It sounds like a low-level detail that I’d like a library to deal for me, with a “block until X (or one of X, Y, or Z) happens” API.
