### ISSUE TITLE
Hash and Eq for Senders?

### ISSUE THREAD

**Issue by birkenfeld** [crossbeam-rs/crossbeam-channel#28]
I was thinking of adding `crossbeam-channel` support to `chan-signal`. A naive port would require Senders to be put into a HashMap, so they'd need to be Hash+Eq. AFAICS, `chan` channels have a unique ID shared by all its senders and receivers.

Is that feasible with crossbeam-channel?

**Comment by stjepang** [comment]
Sure, I'll prepare a PR for `Hash` and `Eq`. Do you think we should implement `Ord` for `Sender` and `Receiver` as well?

**Comment by birkenfeld** [comment]
Thanks! If it's easy to do - I think it wouldn't hurt :)
