### ISSUE TITLE
Unwind safety?

### ISSUE THREAD

**Issue by ArtemGr** [crossbeam-rs/crossbeam-channel#30]
I wonder whether the crossbeam_channel sender is unwind-safe?

**Comment by stjepang** [comment]
Yes, it is unwind-safe.

Note that there is a proposal in #11 that would make it unwind-unsafe, but I'm not sure whether we will accept it. The problem occurs after reserving a slot for sending a message: if you panic before supplying the message, the channel is in a broken state, and a future receive operation will wait for the promised-but-not-supplied message forever (deadlock). That would make the channel unwind-unsafe, if I'm understanding correctly. Do you have an opinion on this matter?

**Comment by ArtemGr** [comment]
Since `drop` destructors are being run during a panic unwind, I'd argue that

```
let msg = "foo".to_string();
let mut sel = Select::new();
loop {
    if let Ok(s) = sel.send(&tx) {
        panic! ("foobar");
        s.finish(msg);
        break;
    }
}
```

isn't any different from

```
let msg = "foo".to_string();
let mut sel = Select::new();
loop {
    if let Ok(s) = sel.send(&tx) {
        if (true) {log! ("A error just happened"); break}
        s.finish(msg);
        break;
    }
}
```

In both the situations we "return early" from the function, forgetting a call to `s.finish`. In the first case the "early return" is caused by the panic, in the non-panicky second case it's caused by the error handling logic.

I expect the channel to implement a `Drop` on `s`, to handle the second case somehow. And if it will, then it should also work for the first panicky case.

Thus I'm not sure I see what the problem is, why would the #11 make the channel any more unwind-unsafe than before?

Am I looking at the wrong place?

**Comment by ArtemGr** [comment]
Thanks for explaining stuff in #11.

Now that I understand the problem a bit better I'm more comfortable proposing the following:
How about marking the `Select` with `UnwindSafe`, but the `s` as `!UnwindSafe` ?

It looks to me like the `Select` can be passed around NP, and the only place where the panic-altered code flow might affect things is when the `s` was instantiated.

**Comment by stjepang** [comment]
Sounds good to me! However, I'd probably be a little bit more conservative and mark `Select` as unwind-unsafe as well. But `Sender` and `Receiver` would be unwind-safe, though.

**Comment by ArtemGr** [comment]
Fair enough, thanks for looking into it!

**Comment by ArtemGr** [comment]
Having given it a bit more thought, I'm no longer sure my previous suggestion makes sense.

I have arguments for both total unwind-safety and total lack of it.

An argument for total unwind-safety is that panic won't introduce any broken invariants!

If we call `sel.send` without `s.finish`, receiver will deadlock. There is **no** invariant saying that the receiver won't deadlock, or that `s.finish` is always called after `sel.send`! Deadlock is a normal, non-broken state for this channel. Thus unwinding hasn't broken any invariants and the channel should be marked unwind-safe, `s` and all.

Indeed, unwinding might and should be used to avoid the deadlocks:
```
    if let Ok(s) = sel.send(&tx) {
        let value = catch_unwind (...);
        s.finish(value);
```

---

On the other hand, if we want the unwind-safety rules to somehow prevent the panics from deadlocking the channel ever, then marking the `s` as `!UnwindSafe` won't help there, as the following code still deadlocks:
```
    catch_unwind (move || {
        if let Ok(s) = sel.send(&tx) {
            a_code_that_might_panic();
            s.finish (...);
```

It might be possible to have two versions of the `Sender`, one with the "placement send" and another with the traditional moving send. Then the "placement send" version of the `Sender` might be marked as not unwind-safe in order to prevent the users from shooting themselves in the foot.

But I'd still argue that panic here doesn't put the channel in an invalid state and doesn't introduces any broken invariants, so the channel should simply be marked unwind-safe, with "placement sent" and all.
