### ISSUE TITLE
Rename disconnect to close?

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#32]
Nomenclature in other channel implementations:

* The [`chan`](https://docs.rs/chan/0.1.20/chan/) docs talk about *closing* - there is no mention of *disconnection*.
* The [`std::sync::mpsc`](https://doc.rust-lang.org/std/sync/mpsc/index.html) docs talk about *disconnection*, but there is some mention of *closing* throughout the [code and error messages](https://doc.rust-lang.org/src/std/sync/mpsc/mod.rs.html#11-3014).
* The [`futures::sync::mpsc`](https://docs.rs/futures/0.1.17/futures/sync/mpsc/index.html) docs talk about *disconnection* and *closing* interchangeably. There is the [`close`](https://docs.rs/futures/0.1.17/futures/sync/mpsc/struct.Receiver.html#method.close) method, but also [`is_disconnected`](https://docs.rs/futures/0.1.17/futures/sync/mpsc/struct.TrySendError.html#method.is_disconnected) method.
* [Golang](https://golang.org/ref/spec#Close) talks about *closing* channels. There is no mention of *disconnection*.

I think mixing *closing* and *disconnection* is confusing and we should stick to one term or the other, and be consistent about it. My preference goes toward *closing* since it is more prevalent, shorter to type, and more intuitive (IMO, closing implies nothing can be sent into the channel anymore, while disconnection sounds more hazardous, as if the messages currently buffered in the channel might get dropped).

The main drawback of switching to *closing* consistently is that `{TryRecvError,TrySendError}::Disconnected` would have to be renamed to `{TryRecvError,TrySendError}::Closed`, thus departing from the interface in `std::sync::mpsc`. This could be an annoyance when switching from `std::sync::mpsc` to `crossbeam-channel`.

Since I'm preparing a set of breaking changes for the 0.2 version of `crossbeam-channel`, perhaps we should pull the trigger and switch the nomenclature to *closing*?

**Comment by martinhath** [comment]
👍 for *closing*, for pretty much exactly the reasons you've stated. 😄
