### ISSUE TITLE
add into() implementation for std::sync::mpsc::TrySendError

### ISSUE THREAD

**Issue by vitiral** [crossbeam-rs/crossbeam-channel#34]
## Use Case

I would like for the [`ch!`](https://docs.rs/ergo_sync/0.1.0/ergo_sync/macro.ch.html) macro to be able to move to it's own crate and be usable for _any_ current or future non-blocking channel. ~~I think this would allow it to be usable by a `futures-channel` crate even (maybe with a bit of added syntax for the `Context` argument).~~ (meh, that isn't really known)

## Feature request

Add `into()` to convert to the stdlib type, or use the stdlib type directly.

## Reasoning

As far as I can tell these types are basically identical

-  [std::sync::mpsc::TrySendError](https://doc.rust-lang.org/std/sync/mpsc/enum.TrySendError.html)
```
pub enum TrySendError<T> {
    Full(T),
    Disconnected(T),
}
```

[crossbeam_channel::TrySendError](https://docs.rs/crossbeam-channel/0.1.2/crossbeam_channel/enum.TrySendError.html)
```
pub enum TrySendError<T> {
    Full(T),
    Disconnected(T),
}
```

The same is true for TryRecvErorr (from std):
```
pub enum TryRecvError {
    Empty,
    Disconnected,
}
```

**Comment by vitiral** [comment]
note: I'm willing to implement this if you would like.

**Comment by stjepang** [comment]
Sounds good!

I'd also suggest adding conversions in the opposite direction, for example:
`impl<T> From<mpsc::TrySendError<T>> for TrySendError<T>`

**Comment by vitiral** [comment]
It looks like we should implement From, and the stdlib will implement Into
automatically

https://doc.rust-lang.org/beta/std/convert/trait.Into.html

Library authors should not directly implement this trait, but should prefer
implementing the From
<https://doc.rust-lang.org/beta/std/convert/trait.From.html> trait, which
offers greater flexibility and provides an equivalent Into implementation
for free, thanks to a blanket implementation in the standard library.
