### ISSUE TITLE
Lessons to be taken from channels in Go?

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#39]
I'd like to take a step back and challenge some of the core design decisions in `crossbeam-channel`, `std::sync::mpsc` and `futures::sync::mpsc`.

### Motivation: `select!` for [`crossbeam-channel`](https://docs.rs/crossbeam-channel) is hard to get right 

The current [`select_loop!`](https://docs.rs/crossbeam-channel/0.1.2/crossbeam_channel/macro.select_loop.html) macro is kinda silly (it's a loop, you can't use `break`/`continue` inside it, it causes potentially subtle side effects on every iteration). I'm trying to come up with a new, nicer macro, with fewer surprises, and without the implicit loop.

This is what seems like the best solution so far:

```rust
select! {
    recv(receiver, msg)     => {} // `msg` is of type `T`
    send(sender, foo + bar) => {} // sends message `foo + bar`
    closed(receiver)        => {} // fires when `receiver` is closed
    closed(sender)          => {} // fires when `sender` is closed
    default(timeout)        => {} // fires when `timeout` expires
}
```

And this is how it works:

1. If any of the `recv` or `send` cases can complete without blocking, a random one is chosen. The chosen operation is executed and its block (in this example `{}` for simplicity) is evaluated.
2. If any of the `closed` cases are ready (because a channel is closed), it is evaluated.
3. If the timeout has expired, the `default` case is evaluated.
4. Otherwise, we wait until something changes.

Pros:

* No surprises (apart from the complexity) - it behaves just as one would expect.
* Very flexible - allows a lot of freedom in choosing how to react to channel events.

Cons:

* Using a `recv` or a `send` case doesn't nudge you into handling the `closed` case. For example, this is in contrast to a bare `Receiver::recv` operation, which returns a `Result` so the compiler advises you to do something with it (like call `.unwrap()`).
* The macro looks kind of complicated.
* Internal implementation is a little challenging (although not too bad).

There were some other different ideas for the macro but I won't go there.

Folks from Servo (more concretely, @SimonSapin and @nox) were cool with this macro idea, although it wasn't the absolute best option for their use case.

@matthieu-m had a good point that the `select!` macro should ideally be *exhaustive* in the sense that it makes sure you don't forget edge cases like a channel being unexpectedly closed.

Now let's see if we can somehow force the user to handle the `closed` case for every `recv` and `send`. One idea is to change `recv` so that it returns a `Result<T, RecvError>`:

```rust
select! {
    recv(receiver, msg) => {
        match msg {
            Ok(m) => println!("got {:?}", m),
            Err(RecvError) => println!("the channel is closed"),
        }
    }
}
```

But what about the `send` case? Here's a try:

```rust
let mut greeting = String::new("Howdy!");
select! {
    send(sender, greeting, result) => {
        match result {
            Ok(()) => println!("successfully sent"),
            Err(SendError(m)) => greeting = m,
        }
    }
}
```

That'd work and eliminate the need for `closed` case, but it doesn't look very nice. To be fair, users of this `select!` syntax would typically just raise a panic on 'closed' events:

```rust
let mut greeting = String::new("Howdy!");
select! {
    recv(receiver, msg) => {
        let m = msg.expect("the channel is closed");
        println!("got {:?}", m),
    }
    send(sender, greeting, result) => {
        result.expect("the channel is closed");
    }
}
```

Looks a bit better, but still kind of clumsy.

### When does a channel become closed/disconnected?

Depends on the implementation.

* In `std::sync::mpsc`: when either the `Receiver` or all `Senders` get dropped.
* In `crossbeam-channel`: when either all `Receiver`s or all `Sender`s get dropped.
* In `futures::sync::mpsc`: when either the `Receiver` or all `Sender`s get dropped, or when you call `Receiver::close`.
* In [`chan`](https://docs.rs/chan): when all `Sender`s get dropped.
* In Go: when you call `close(sender)`. It is not possible to close from the receiver side.

These differences are important. The `chan` crate follows Go's model very closely so they have very similar behavior. The reason why Go allows closing from the sender side is because it follows the principle of *unidirectionality*.

Unidirectionality means that information flows in one direction only. Closing a channel signals to the receivers that no more messages will arrive, ever. Note that even if all receivers get dropped, sending into the channel works as usual. The whole idea is that receiver side cannot signal anything to the sender side!

Why do we want unidirectionality? See [this](https://github.com/golang/go/issues/14601#issuecomment-191421028) and [this](https://github.com/golang/go/issues/11344#issuecomment-117862884) comment by Russ Cox for an explanation.

### Channels in Go

Channels in Go are quite peculiar. They come with a bunch of rules that seem arbitrary at first sight, but are actually well-thought-out. See [`Channel Axioms`](https://dave.cheney.net/2014/03/19/channel-axioms) and [`Curious Channels`](https://dave.cheney.net/2013/04/30/curious-channels) by Dave Cheney. The controversial blog post titled [Go channels are bad and you should feel bad](https://www.jtolds.com/2016/03/go-channels-are-bad-and-you-should-feel-bad/) is worth a read, too, despite the title.

Here are a few interesting rules:

1. Sending into a closed channel panics. The idea is that senders have to coordinate among themselves so that the last sender closes the channel.

2. Receiving from a closed channel returns a 'zero value'. This is like returning `None`, but Go doesn't have sum types.

3. Sending into a `nil` channel blocks forever. This is handy when you want to disable a send operation inside a `select` - just set the sender to `nil`! 

4. Receiving from a `nil` channel blocks forever. This is useful for the same reason the previous rule is. See [this](https://stackoverflow.com/questions/13666253/breaking-out-of-a-select-statement-when-all-channels-are-closed/13666733#13666733) StackOverflow answer for an example.

### How would we port Go's channels to Rust

Let's solve some of the quirks in Go's channels by using two useful language features of Rust: destructors and sum types.

Keeping the idea of unidirectionality, we change the disconnection behavior: channel gets closed only when all `Sender`s get dropped. That's it. This means sending into a channel cannot panic because having a sender implies the channel is not closed. Next, receiving from a closed channel returns an `Option<T>` rather than a 'zero value'. The `chan` crate follows the same design - see [here](https://docs.rs/chan/0.1.21/chan/struct.Sender.html#method.send) and [here](https://docs.rs/chan/0.1.21/chan/struct.Receiver.html#method.recv).

I'm feeling very tempted to redesign `crossbeam-channel` around the philosophy of Go channels:

```rust
impl<T> Sender<T> {
    fn send(&self, msg: T);
}

impl<T> Receiver<T> {
    fn recv(&self) -> Option<T>; // `None` if closed.
}

let greeting = String::new("Howdy!");
select! {
    recv(receiver, msg) => {
        // `msg` is of type `Option<T>`
        let m = msg.expect("the channel is closed");
        println!("got {}", m);
    }
    send(sender, greeting) => {
        println!("successfully sent");
    }
    default(timeout) => println!("timed out!"),
}
```

This is beautifully simple:

* Easy to understand, especially for programmers coming from the world of Go.
* No need for those annoying `unwrap`s in `sender.send(foo).unwrap()`. @BurntSushi is going to like this. :)
* `select!` macro doesn't need the `closed` case.
* You're advised to handle the possibility of the channel being closed in the `recv` case. Perhaps we might want to change the `Option` type to `Result`.

Some drawbacks:

* Dropping all receivers doesn't prevent senders from sending. This might or might not be a drawback - we could argue both ways.
* `select!` is not as powerful as before. But it probably doesn't matter since all real-world cases should be covered by this simpler version.

Note that we could also accept `Option<Sender<T>>` and `Option<Receiver<T>>` in the `recv` and `send` cases. That would be equivalent to using `nil` channels in Go.

We can get all the benefits of Go channels without its weak spots like accidental panics (e.g. sending into a closed channel), accidental deadlocks (e.g. receiving from a `nil` channel), and incorrect closing (we close automatically when the last `Sender` gets dropped).

### Final words

The simple `Go`-like channel interface currently seems to me to be sitting in some kind of sweet spot of the design space. I've been thinking about this problem for way too long now, constantly switching from one idea to another. In the end, I'm not sure whether this one is the way to go and need your opinion. 

Any thoughts?

cc @arcnmx - you might be interested in this comment, too.

**Comment by stjepang** [comment]
To answer [this comment](https://github.com/rust-lang-nursery/futures-rs/issues/800#issuecomment-370192929) from @danburkert:

I cannot dispute any of your points - they all seem fair. In particular, `Sender::close()` does seem like a useful method. Regarding `Sender::send()`, I understand the concern, but then again, @BurntSushi (and many others, I'd wager) would probably disagree.

Currently, the main goal of `crossbeam-channel` is to be a sort of a 'mega-channel' that can do pretty much anything and doesn't impose any artificial restrictions on the user. It's just that I've come to question this goal now that certain complexities inside `select!` have showed up.

**Comment by glaebhoerl** [comment]
I think I'd like to hear more argumentation about why unidirectionality is a *desirable* property rather than merely a *sensible* one. 

From the link:

> There almost always need to be two steps in a cancellation: a request for the cancellation and an acknowledgement that work has in fact stopped. Close can serve as the latter; it cannot serve as both, and we make it as hard as possible for people to do that accidentally.

Maybe somebody can elaborate on what this means and why? It seems to me that the receiver doing a `close()` followed by the sender detecting the failure of its `send` and reacting appropriately could serve as those two steps, at least under one way of interpreting them. (Is the "cannot serve as both" claim only intended to be true within the context of Go, e.g. because it happens to have no way to detect the failure of a send, or is it something more fundamental?)

And as a potential counterpoint to unidirectionality: I'm sure many of us have noticed the symmetry between:

```rust
impl Sender<T> {
    fn send(&self, value: T) -> Result<(), T>;
}
impl Receiver<T> {
    fn recv(&self) -> Result<T, ()>; // could be thought of as having `value: ()`!
}
```

It's almost as if these can be generalized to:

```rust
struct Endpoint<A, B> { ... }
impl Endpoint<A, B> {
    fn new() -> (Endpoint<A, B>, Endpoint<B, A>);
    fn rendezvous(&self, value: A) -> Result<B, A>;
}
type Sender<T> = Endpoint<T, ()>;
type Receiver<T> = Endpoint<(), T>;
```

Which is what OCaml is [thinking about doing](http://kcsrk.info/slides/reagents_edinburgh.pdf). Of course, as I meant to imply with the name there, this only makes sense for 0-buffered channels. But, at least, it suggests to me that bidirectionality can *also* be a sensible property.

**Comment by stjepang** [comment]
> I think I'd like to hear more argumentation about why unidirectionality is a *desirable* property rather than merely a *sensible* one.

Unidirectionality is strictly less powerful than bidirectionality, so one can only argue for it from the standpoint of simplicity and ergonomics.

Unidirectionality makes selection straightforward. Any operation declared inside a `select` will behave exactly as if it was a standalone operation (outside `select`). No surprises there.

With bidirectional closing, however, we have to introduce a special `closed` case in `select`, which will not be automatically enforced, unfortunately. Alternatively, we must reach for more complicated variants of `recv` and `send` cases, which adds a considerable penalty on ergonomics.

In one sentence, unidirectionality makes the interface smaller, simpler, and more consistent (in terms of `select` vs standalone operations, at least).

> Maybe somebody can elaborate on what this means and why? It seems to me that the receiver doing a close() followed by the sender detecting the failure of its send and reacting appropriately could serve as those two steps, at least under one way of interpreting them.

My understanding is that in Go this is simply considered an antipattern.

If any send operation can fail, that means most users will just ignore the error and prefer to panic instead. Basically every use of channels in Rust is littered with `.unwrap()`s, which sometimes looks silly. This is reminding of tedious `.unwrap()`s one has to write after locking a `Mutex`, which prompted some people to create `Result`-free `Mutex`es as in [`antidote`](https://docs.rs/antidote/1.0.0/antidote). [`parking_lot`](https://docs.rs/parking_lot/0.5.4/parking_lot/) decided to do away with `Result`s, too. The [`chan`](https://docs.rs/chan/0.1.21/chan/struct.Sender.html#method.send) crate sends into a channel without a `Result`, too.

Also, signalling to the sender that the receiver is shutting down is not hard to do using a 0-capacity channel anyway, and may lead to cleaner design. At least the Go team believes so.

Finally, it's interesting to ponder how one would actually implement closing a channel. In Go, each channel is wrapped into a single mutex so there's a `closed: bool` flag in there, but what if we had a lock-free queue and no mutexes behind the scenes? While it's tempting to use a `closed: AtomicBool` flag, that would be wrong and cause linearizability issues. Instead, a close operation in `crossbeam-channel` [marks a bit](https://github.com/crossbeam-rs/crossbeam-channel/blob/2edbf01725a6cf1ad00d8d64ca3c4a930e7f0205/src/flavors/array.rs#L414) of the sender index.

Note that *close a channel* is literally a synonym for *freeze the sending side*. Since closing a channel is only concerned with the sending side, perhaps only the sending side should be allowed to close? The answer to this question probably depends on whether your mental model of a channel is *a simple queue* or *like a unix pipe where both sides can signal closing*.

> (Is the "cannot serve as both" claim only intended to be true within the context of Go, e.g. because it happens to have no way to detect the failure of a send, or is it something more fundamental?)

While Go doesn't have a way to detect failure of a send operation, they could've easily implemented this feature (e.g. `ok := channel <- msg`). To omit the feature was a deliberate decision.

> Which is what OCaml is thinking about doing. Of course, as I meant to imply with the name there, this only makes sense for 0-buffered channels. But, at least, it suggests to me that bidirectionality can also be a sensible property.

This is an interesting example. Indeed, the symmetry is beautiful. However... :) 

I've done a lot of research on queues and channels in other languages and libraries. They will often boast about performance, features, and so on. The rosy story always falls apart when it comes to select. Go is the only language where channel selection is simple, easy, and *just works*. Many channel implementations don't have any kind of selection at all! Let's take a look at the `mpsc_select` feature in Rust as an example. The [macro](https://doc.rust-lang.org/std/macro.select.html) has fragile syntax (poor compilation errors), only accepts receive operations (no sends!), and has seen no progress in years. The macro will is basically deprecated (see [here](https://github.com/rust-lang/rust/issues/12902#issuecomment-319510050) and at this point it is only kept alive because Servo still depends on it.

The [`chan`](https://github.com/BurntSushi/chan) crate is an alternative that sacrifices performance, but provides a nice Go-like interface with proper `chan_select!` macro. Apart from a few quirks and bad performance, it works very well. In 2015, [a request](https://github.com/BurntSushi/chan/issues/2) for adding a `send` operation returning a `Result` was submitted. @BurntSushi was originally hesitating:

> The second design decision I made was, "sending a value that can never be received is either a bug or an intentional leak." This may be a bad decision, but it is one that has a large body of evidence that suggests it may not be a horrible idea. (e.g., Go.) The idea here is too encourage users of chan to write code that doesn't enter that state. I was motivated to do things this way because so many uses of the std::sync::mpsc channel are tx.send(...).unwrap(). In other words, it makes the common case verbose.

In the end, he was sold on the feature request and decided to implemented the non-panicking send method. However, it turned out that fitting the concept of non-panicking send into `chan_select!` was a very difficult design problem, and that's where the story ends.

`crossbeam-channel` is a successor to `chan` and `std::sync::mpsc`. I've put a lot more time and effort into its development and managed to overcome some key difficulties other channels have run into. However, when it comes to selection, now I'm facing the infamous selection problem. There seem to be only two ways forward:

1. Keep the `std::sync::mpsc`-like design and implement a complicated `select!`.

2. Take a more opinionated stance and implement `chan`/Go-like channels with simple `select!`.

**Comment by BurntSushi** [comment]
@stjepang It was a joy reading your comments in this thread, and I can definitely identify with your toil. However, when I wrote `chan`, I took a b-line straight to what I knew worked: Go's channels. I didn't even come *close* to exploring the design space as thoroughly as you have. Speaking as someone who has written Go for a very long time, and worked with others that have written Go, its channel implementation has been a raging success from my perspective. There are lots of downsides (all of which you are clearly aware of), but it works well. So with that said, I think my vote would be towards being opinionated. The reasoning is simple: `select` is the single most important aspect of an ergonomic channel implementation, and if people have trouble using it, it's always going to compare unfavorably to other choices (like Go's).

One thing that came up towards the end of https://github.com/BurntSushi/chan/issues/2 was what to do when a channel send occurs on a non-closed channel that is guaranteed to never be received. `chan` today will lock forever, which is what Go will do. However, it seems possible that you could panic in that case, and indeed, if Go's runtime detects that no goroutine will make progress, it will actually panic because it effectively detected a deadlock. To keep select simple, you could simply not expose this panic at all and keep the `send() -> ()` type signature.

**Comment by matthieu-m** [comment]
After thinking for a longer moment about `send()` failure, I think bi-directionality is weirder than I initially thought.

I have used (distributed) queuing systems quite extensively for nigh on 5 years at my previous job: I was actually developing the middleware applications on top of them, which were used among other things to... make sure that the luggage you drop at the departure airport arrives at destination. One of the most important properties of our queuing systems was *to never lose an item*. A queue which acknowledges an item but fails to deliver it was buggy, plain and simple.

Which is why closing from the receiving side is slightly weird. Even if the senders immediately stop sending, what of all the items in flight?

To design a queue which does not lose items, the receiving side must "request" a close, and then *continue processing* until it is guaranteed that no other item will be enqueued. This is easily implemented if the queue is locked for each send/receive, but faster implementations are preferred, and then things become racy.

And suddenly, we seem very close to the unidirectionality advocated by Go: the receiver may only *signal an intent*, the senders decide when to stop.

Also, note that an absence of receiver should *not necessarily fatal*. That is, even if the receiver dies (unexpected data in the queue causes a panic which unwinds the thread), it may be desirable to have the ability to spawn a new receiver to continue processing. Being able to use the current queue (already wired in on the sender side, already containing some non-processed items) is quite desirable then.

**Comment by stjepang** [comment]
@BurntSushi 

> One thing that came up towards the end of https://github.com/BurntSushi/chan/issues/2 was what to do when a channel send occurs on a non-closed channel that is guaranteed to never be received. `chan` today will lock forever, which is what Go will do. However, it seems possible that you could panic in that case, and indeed, if Go's runtime detects that no goroutine will make progress, it will actually panic because it effectively detected a deadlock. To keep select simple, you could simply not expose this panic at all and keep the `send() -> ()` type signature.

I like this idea. So basically when sending into a bounded channel that is full and has no receivers left, rather than waiting forever, we panic with an appropriate message. Sounds good to me! We could do something similar in `select!`, too.

By the way, I'm sure you know the pains of dealing with poor error messages due to trivial mistakes in macros. Well, you're going to like [this](https://gist.github.com/stjepang/5ccb7199dca02ddf5f3087da2451efa9). :)

An example:

```rust
select! {
    recv(r, msg) => msg,
    send(s, 1 + 2) => println!("sent")
    default(timeout) => ()
}
```

Error message:

```
error: did you mean to put a comma after `println!("sent")`?
```

The new macro seems to give a sensible message no matter what kind of mistake I try planting in there, and isn't nitpicky about things like trailing commas. I'm pleasantly surprised to discover that macros can be so friendly at all!

@matthieu-m

Thank you for the comment! This is a very compelling argument in favor of Go-like channels, in my opinion. I find the parts about draining the remaining messages and spawning a new receiver pretty convincing.

In the end, reacting to the automatic close signal when all receivers go away is probably not the most robust way of shutting down anyway. I think this is the key point Russ Cox was trying to get across in his comments.

I'd just like to add a demonstration of how it's still easy to implement a signal in the backwards direction if one needs it:

```rust
let (sender, receiver) = channel::unbounded();
let (signal, done) = channel::bounded(0);

// The producer thread.
thread::spawn(move || {
    while !done.is_closed() {
        select! {
            recv(done) => break,
            send(sender, generate_message()) => (),
        }
    }
    // Do something with the remaining messages.
    // Maybe spawn a new worker thread?
});

// The worker thread.
thread::spawn(move || {
    let signal = signal; // Will get dropped when this thread exits.

    for msg in receiver {
        if process_message(msg).is_err() {
            // Something went wrong. Shut down.
            break;
        }
    }
}
```

@danburkert

> The receiver keeps receiving buffered items until there are no more, at which point further calls to recv indicate that the channel has been closed.

This confuses me, too. Perhaps @matthieu-m meant to write the following?

*Which is why closing from the receiving side is slightly weird. Even if the receivers immediately stop receiving, what of all the items in flight?*

**Comment by BurntSushi** [comment]
> By the way, I'm sure you know the pains of dealing with poor error messages due to trivial mistakes in macros. Well, you're going to like this. :)

Wow. I had no idea that was possible. :heart_eyes:

**Comment by coder543** [comment]
@BurntSushi considering that I sent a pull request like 5 months ago [that does the same thing for `chan`...](https://github.com/BurntSushi/chan/pull/23) Idk. I just thought you might have at least looked at the PR at some point. :/

@stjepang after reading all of this discussion and thinking about it, I'm starting to lean towards the opinionated, unidirectional channel interface, even though I would have said it makes sense for the receiver to be able to close the channel. The one question I have with that: what happens if the receiver thread panics? Does the sender just keep adding items to the channel's buffer? As @matthieu-m said, losing the items in flight would not be good, but I'm not sure how you would approach creating a new receiver into the same channel from a dead thread, from an API perspective.

**Comment by BurntSushi** [comment]
> considering that I sent a pull request like 5 months ago that does the same thing for chan... Idk. I just hoped you might have at least looked at the PR at some point. :/ oh well.

Sorry, but with the volume of PRs/emails I get that are blocked personally on me, some of them just fall through the cracks. PRs that touch write-once code that I no longer understand naturally go to the bottom of my list, and are often forgotten about unless someone makes noise. It's just the way it is.

**Comment by stjepang** [comment]
@coder543 

> but I'm not sure how you would approach creating a new receiver into the same channel from a dead thread, from an API perspective. If there is a solution, that would be interesting to see.

Perhaps something like this?

```rust
fn producer(chan: Channel, ) {
    let (s, r) = bounded(BUFFER);
    let (alive, mut dead) = bounded(0);
    let mut t = thread::spawn(consumer(r.clone(), alive));

    while !finished() {
        let msg = produce_message();

        select! {
            send(s, msg) => {}
            recv(dead, _) => {
                let (alive, d) = bounded(0);
                dead = d;
                t = thread::spawn(consumer(r.clone(), alive));
            }
        }
    }

    drop(r);
    t.join().ok();
}

fn consumer(r: Receiver<Message>, alive: Sender<()>) {
    for msg in r {
        consume_message(msg); // may panic
    }
}
```
