### ISSUE TITLE
Syntax for timeouts in select

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#46]
Now that #41 is almost finished, I'm thinking about the syntax for timeouts in the new `select!` macro. There are two options I'm exploring:

### First option

```rust
let timeout = Duration::from_secs(1);
select! {
    recv(r, msg) => println!("got {:?}", msg),
    default(timeout) => println!("timed out"),
}
```

The `default` case optionally accepts a timeout (of type `Duration`) or a deadline (of type `Instant`). It can also accept `Option<Duration>` and `Option<Instant>`, where `None` simply means the `default` case will never get fired.

### Second option

We define these two helper functions like in Go and `chan` crate:

```rust
fn after(dur: Duration) -> Receiver<()>;
fn tick(dur: Duration) -> Receiver<()>;
```

The `default` case now doesn't accept any arguments, but one can still handle timeouts by creating a channel using one of the two helper functions:

```rust
let timeout = Duration::from_secs(1);
select! {
    recv(r, msg) => println!("got {:?}", msg),
    recv(channel::after(timeout)) => println!("timed out"),
}
```

Functions `after` and `tick` don't spawn threads - they're very cheap and don't allocate anything (the logic is handled in a special receiver variant), so there would be no concerns about performance like in `chan` crate.

-----------

So the questions are:

1. Should `default` be able to accept a timeout/deadline as an argument?
2. Do we need functions `after` and `tick`?

cc @BurntSushi Do you have an opinion on this?
cc @tekjar You asked for ticker in #36. Any thoughts about this idea?

**Comment by BurntSushi** [comment]
I think I would prefer the second option since it seems more composable.

**Comment by tekjar** [comment]
Wow really excited about the new implementation. 

I'll get back to this after a quick go `select` refresher :)

**Comment by stjepang** [comment]
@tekjar 

> Go select seems to be supporting these 3

Actually, Go has only tickers and timers. There isn't a special syntax for timeouts, but you can specify a timeout in select by receiving from a timer (`time.After`), e.g. as described here: https://gobyexample.com/timeouts

> Can I set multiple tickers, timeouts with the first option? 

No, the first option allows you to specify only a single timeout or deadline.

> How about combining both option1 and option2?

If we go with option 2, then it probably isn't worth implementing option 1, since `default(timeout)` would be equivalent to `recv(after(timeout))`. :)

At the moment, my feeling is that we should go with option 2 because it's more powerful and probably more familiar to Go users...
