### ISSUE TITLE
Complex wording

### ISSUE THREAD

**Issue by Cosaquee** [crossbeam-rs/crossbeam-channel#51]
I know that this might be weird issue but I decided to create it anyway. 

`A channel can be created by calling bounded or unbounded. The former creates a channel of bounded capacity (i.e. there is a limit to how many messages it can hold), while the latter creates a channel of unbounded capacity (i.e. it can contain an arbitrary number of messages).`

While reading documentation this sentence was pretty complicated to understand and I needed to check the meaning of `the former`  and `the latter`. I think that a lot of non English native people might have problems with that construct.

If you think this is not a problem, feel free to close this issue.

**Comment by stjepang** [comment]
I'm not a native English speaker either. :) Do you have a suggestion for more understandable wording?

**Comment by Cosaquee** [comment]
I think `first one` and `second one` could be easier to understand. I`m not sure but it seems easier for at least.
