### ISSUE TITLE
Stop selection if *any* channel becomes disconnected.

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#6]
I've noticed that `ipc-channel` relies on this behavior in `std::sync::mpsc::Select`: [link to code](https://github.com/servo/ipc-channel/blob/eab8063b7c42f4bf62595af69f7bf1339cb29c33/src/platform/inprocess/mod.rs#L177).

The call to `select.wait()` will wake up even if just one channel becomes disconnected. This is something `crossbeam-channel`'s selection cannot do right now. We can only wake up when *all* channels become disconnected.

Perhaps we should have two kinds of disconnection cases, `all_disconnected()` and `any_disconnected()`? (these names are not great so I need better ideas)

cc @TimNN

**Comment by TimNN** [comment]
I'm generally bad at coming up with names ;) I personally don't really mind `(all|any)_disconnected`, they precisely describe what they do.

An alternative would be to have a generalized `fn disconnected(remaining: usize)` which would only trigger if a (a) disconnected has just happened and (b) the number of remaining channel is less than (or equal to) the given number. So you could use `disconnected(0)` for `all_disconnected` and `disconnected(usize::max_value())` for `any_disconnected`.

**Comment by stjepang** [comment]
Here's another idea.

Cases in `select_loop!`:

* `disconnected()` - fires when all channels get disconnected.
* `disconnected(tx)` - fires when `tx` gets disconnected.
* `disconnected(rx)` - fires when `rx` gets disconnected.
* `disconnected(tx1, rx2, tx3)` - fires when any one of `tx1`, `rx2`, `tx3` get disconnected.
* `disconnected(..)` - fires when any channel gets disconnected.

Cases in `select`:
* `disconnected()`
* `disconnected_rx<T>(rx: Receiver<T>)`
* `disconnected_tx<T>(tx: Sender<T>)`

**Comment by SimonSapin** [comment]
When waking up because any channel is disconnected, we presumably want to know which one. So rather than an `any_disconnected(&mut self) -> bool` method, maybe what’s needed is variants of the `recv` and `send` methods whose return value distinguish the case where that particular channel is disconnected v.s. the case where the message was not sent/received yet.

**Comment by stjepang** [comment]
@SimonSapin 

That sounds like a good idea, but I have don't know how to make the API reasonably nice. Here's a try (very poor one):

```rust
impl Select {
    fn recv<T>(&mut self, rx: &Receiver<T>)
        -> Result<Result<T, RecvError>, SelectRecvError>;

    fn send<T>(&mut self, tx: &Sender<T>)
        -> Result<Result<(), SendError<T>>, SelectSendError>;

    // ...
}
```

But that's pretty ugly. Any better ideas?

I believe we should add the following cases instead, which keeps selection simple enough:

```rust
impl Select {
    fn disconnected_rx<T>(&mut self, rx: &Receiver<T>) -> bool;

    fn disconnected_tx<T>(&mut self, tx: &Sender<T>) -> bool;

    // ...
}
```

What do you think -- should we try that?

**Comment by SimonSapin** [comment]
`Select*Error` are zero-size, right? Is this important that this is a Result rather than Option? `Option<Result<…>>`` doesn’t seem too bad to me.

Your alternative works too, it just doubles the number of lines in `select_loop!`.

**Comment by stjepang** [comment]
Another idea:

```rust
select_loop! {
    // The question mark indicates this case fires when a message is
    // received or the channel is disconnected.
    recv(rx, option_msg)? => {
        // The received value `option_msg` is of type `Option<T>`.
        let msg = option_msg.expect("the channel got disconnected");
        println!("Message: {:?}", msg);
    }
}
```

**Comment by SimonSapin** [comment]
Oooh I like the question mark.

**Comment by stjepang** [comment]
The problem with the last suggestion is that I don't know how to make an equvalent `send?` case: we need some way of figuring out whether `send?(tx, msg)` succeeded or the channel got disconnected.

Here's another try:

```rust
select_loop! {
    // The question mark indicates this case fires when a message is
    // received or the channel is disconnected.
    recv?(rx, msg) => {
        println!("Message: {:?}", msg);
    } else {
        panic!("the channel is disconnected");
    }

    send?(tx, make_message()) => {
        println!("The message was sent");
    } else {
        panic!("The channel is disconnected");
    }
}
```

Now the question mark is actually redundant, but perhaps makes it clearer that we're also handling the case of channel getting disconnected?

Thoughts on this syntax? Any other suggestions?

**Comment by birkenfeld** [comment]
While working on converting `chan-signal` examples to use `crossbeam-channel`, I've also come across this: they rely on the fact that `recv()` produces an `Option` which is None on disconnect. This is quite elegant combined with signal channels. In `crossbeam-channel`, because signal channels they are *never* closed, you can't use the `disconnected` case in a `select_loop!` at all.

**Comment by stjepang** [comment]
Lately, I've been thinking a bit more about channels in Go - maybe we could steal a few ideas from it? Here's an idea for the new macro (note the comparison to Go in the comments):

```rust
// Note that this is not a loop anymore.
//
// I believe there is a way to avoid running the user-specified code
// multiple times in the loop, so we could have a real `select!` macro
// instead of the current funny `select_loop!` macro.
select! {
    // Receive a message from `rx1`.
    //
    // Equivalent to `case msg <- rx1` in Go.
    //
    // The receiver can also be of type `Option<Receiver<T>>`. Specifying
    // `None` for the receiver simply disables this case. That would be
    // the equivalent of receiving on a `nil` channel in Go.
    recv(rx1, msg) => {}

    // Receive a message from `rx2`, or receive `None` if disconnected.
    //
    // Equivalent to `case msg, ok <- rx1` in Go.
    recv?(rx1, option_msg) => {}

    // Send a message into `tx`.
    //
    // Equivalent to `case tx <- msg` in Go.
    //
    // Maybe we should allow optional senders in `send`, too? I'm not sure.
    send(tx, msg) => {}

    // The default case.
    //
    // Equivalent to `default` in Go.
    //
    // The timeout is an optional argument. If specified, this case will
    // fire when we time out. If not specified, this case is like `would_block`.
    //
    // The timeout can also be of type `Option<Duration>`, where `None`
    // means the timeout is infinite. Put another way, `None` simply
    // disables this case in the same way `recv?(None, _)` would disable
    // that receive case.
    default(Duration::from_millis(100)) => {}
}
```

How about this proposal?

Before we settle with a new interface for selection, I'd like to push support for futures first, which might teach us a few lessons. I believe futures-based selection and native thread-based selection (using a macro) should more-or-less mirror each other. Ideally, the only difference should be at what level of concurrency they operate - either task-level or thread-level concurrency.

**Comment by SimonSapin** [comment]
I’m not familiar with Go or its channels, but I like this proposal. Supporting `recv?` would unblock Servo.

**Comment by nox** [comment]
What about making `recv` panic and `try_recv` return a `Result<T, E>`?

**Comment by stjepang** [comment]
@nox Ideally `recv(...)` inside a `select!` and the `Receiver::recv` method should behave as similarly as possible in order not to confuse users and cause accidental bugs, panics, or forgotten error cases.

If `select! { recv(r, msg) => {} }` could panic, that'd be a bit inconsistent with `Receiver::recv`. The latter returns a `Result` and forces you to do something with it - e.g. if you want to panic, you can call `.unwrap()` explicitly.

Having a `try_recv(r, msg)` case where `msg: Result<T, E>` is a good idea, although the naming choice is slightly misleading. Method `Receiver::try_recv` is just the non-blocking version of `Receiver::recv`, but under this proposal `select! { try_recv(r, msg) => {} }` could actually block.
