### ISSUE TITLE
Select over multiple receivers with different types

### ISSUE THREAD

**Issue by tecywiz121** [crossbeam-rs/crossbeam-channel#63]
I'm writing a small library to aggregate and report different types of events to a collection server.

In crossbeam-channel 0.2.1 I could store receivers of different message types in one collection:

```rust
trait ErasedChannel: Send {
    fn recv(&mut self, select: &mut Select) -> Result<(), SelectRecvError>;
}

struct Channel<V> {
    rx: Receiver<V>,
    reporter: Report<V>,
}

impl<V> ErasedChannel for Channel<V>
where
    V: Send,
{
    fn recv(&mut self, select: &mut Select) -> Result<(), SelectRecvError> {
        let msg = select.recv(&self.rx)?;
        self.reporter.report(msg);
        Ok(())
    }
}

pub struct Collector {
    channels: Vec<Box<ErasedChannel>>,
}

impl Collector {
    fn aggregate(&mut self, deadline: Instant) {
        'aggregating: loop {
            // Convert deadline into duration for select's timeout
            let timeout = match Instant::now() {
                x if x < deadline => deadline - x,
                _ => break 'aggregating,
            };

            let mut select = Select::with_timeout(timeout);

            'selecting: loop {
                for mut channel in &mut self.channels {
                    if let Ok(_) = channel.recv(&mut select) {
                        break 'selecting;
                    }
                }

                if select.timed_out() {
                    break 'selecting;
                }
            }
        }
    }
}
```

Is it possible to achieve something similar with crossbeam-channel 0.3?

**Comment by stjepang** [comment]
Unfortunately, this isn't possible in the new version. :(

Would it be difficult to find a workaround, i.e. an alternative solution that doesn't erase types?

**Comment by tecywiz121** [comment]
I don't doubt that it's possible, but I'm not sure how to proceed.

The actual message types are determined by the application: one struct per event type. In a separate thread, I select over all the receivers to aggregate/report the events.

Without type erasure, I don't think I can cram all the receivers into one list.

**Comment by tecywiz121** [comment]
Alright, so I've been playing around with this for a while now, and the best I can come up with is providing a macro that generates the select from the types provided.

I guess it would look something like:

```rust
selector!(MySelector; Event1, Event2, Event3);
```

Which would expand to something like:

```rust
pub struct MySelector {
    Event1: Channel<Event1>,
    Event2: Channel<Event2>,
    Event3: Channel<Event3>,
}

impl Select for MySelector {
    fn select(&self, _timeout: Instant) {
        select! {
            recv(self.Event1.rx, msg) => self.Event1.recv(msg),
            recv(self.Event2.rx, msg) => self.Event2.recv(msg),
            recv(self.Event3.rx, msg) => self.Event3.recv(msg),

            /* ... skipping the timeout bits ... */
        }
    }
}
```

Which is... okay, but not ideal. It would require making a ton of implementation details public, and I believe that users of my library would have to `#[macro_use] extern crate crossbeam_channel` to get the `select!` macro.

Do you have any suggestions for making this a little cleaner?

**Comment by stjepang** [comment]
Yeah, that doesn't seem like a satisfying solution.

For comparison, this is how one might do dynamic selection in Go: https://stackoverflow.com/questions/19992334/how-to-listen-to-n-channels-dynamic-select-statement

I wonder whether we should do something similar. Suppose `crossbeam-channel` had the following:

```rust
struct SelectCase<'a>;

impl<'a> SelectCase<'a> {
    fn recv<T>(
        r: &'a Receiver<T>,
        callback: impl FnOnce(Option<T>),
    ) -> Self;

    fn send<T>(
        s: &'a Sender<T>,
        message: impl FnOnce() -> T,
        callback: impl FnOnce(),
    ) -> Self;
}

fn select(
    cases: impl IntoIterator<Item = SelectCase>,
    may_block: bool,
) -> bool;
```

Then you could achieve what you had with version 0.1 like this:

```rust
trait ErasedChannel: Send {
    fn case<'a>(&'a self) -> SelectCase<'a>;
}

struct Channel<V> {
    rx: Receiver<V>,
    reporter: Report<V>,
}

impl<V> ErasedChannel for Channel<V>
where
    V: Send,
{
    fn case<'a>(&'a self) -> SelectCase<'a> {
        SelectCase::recv(&self.rx, |msg| self.reporter.report(msg.unwrap()))
    }
}

pub struct Collector {
    channels: Vec<Box<ErasedChannel>>,
}

impl Collector {
    fn aggregate(&mut self, deadline: Instant) {
        let duration = match Instant::now() {
            x if x < deadline => deadline - x,
            _ => return,
        };
        let timeout = after(duration);
        let mut timed_out = false;
        
        while !timed_out {
            let cases = self.channels
                .iter()
                .map(|c| c.case())
                .chain(iter::once(SelectCase::recv(&timeout, |_| timed_out = true)));
            select(cases, true);
        }
    }
}
```

Playground link: https://play.rust-lang.org/?gist=5164b46a2fb04a2611a99cc59be2b1e7&version=stable&mode=debug&edition=2015

What do you think? The proposed `SelectCase` API is the first thing that came to my mind so if you have other ideas, let me know. :)

**Comment by tecywiz121** [comment]
So `SelectCase` is kind of like a way to register the callbacks for each `Sender`/`Receiver`?

If so, I really like it! I'd have to play around a bit to make sure it works, and to get a feel for it, but the idea is pretty simple.

Is it possible to avoid rebuilding the iterable of cases every select operation? Maybe instead of `IntoIterator`, use a slice? I don't know how expensive building that list is, but it seems worth avoiding if we can.

**Comment by stjepang** [comment]
Yes, `SelectCase` is just like `recv(r, msg) => block` or `send(s, msg) => block` inside `select!`. Callbacks are used to produce the message in `send` and to execute the block on success.

We could avoid rebuilding the iterator of cases, but then `FnOnce` would have to be changed to `FnMut`. I'll think a little bit more about this.

Another unresolved question is what should `fn select` return. Here's another idea:

```rust
fn select(
    cases: impl IntoIterator<Item = SelectCase>,
    allow_blocking: bool,
) -> Result<usize, WouldBlock>; // On success, returns the index of the selected case.
```

Yet another:

```rust
fn select(cases: impl IntoIterator<Item = SelectCase>) -> usize;

fn select_nonblocking(
    cases: impl IntoIterator<Item = SelectCase>,
) -> Result<usize, NotReady>;
```
