### ISSUE TITLE
Stopping a receiver when other receiver is active

### ISSUE THREAD

**Issue by tekjar** [crossbeam-rs/crossbeam-channel#67]
Hi @stjepang . I'm planning to write an mpsc abstraction over crossbeam channel to serialize data in the channel to disk when the channel is full. So my sender looks like this

```
struct Sender {
    tx: crossbeam_channel::Sender,
    rx: crossbeam_channel ::Receiver
}
```

```
struct Receiver {
   rx: crossbeam_channel::Receiver
}
```

When sender's `try_send` throws a channel full error, I want to use sender's `rx` to serialize data to disk. But to maintain ordering, I want the other receiver to block when the backup is going on. Is there a better way than using an atomic pointer to check if the queue backup is in progress?

Sorry if this is a wrong place for these questions

**Comment by stjepang** [comment]
Sorry for the late reply!

Yeah, I think it'd be best to communicate the activity of backup going on through a separate atomic flag. There are surely multiple ways to do this. Did you figure out a good solution?

**Comment by tekjar** [comment]
> Sorry for the late reply!

No problem :). I know you are busy with tokio :)

> Did you figure out a good solution?

Not yet. I haven't gone through the code thoroughly yet but one idea is to check if I can modify `crossbeam-channel`'s internals to point `Receiver::rx` to the tail of internal queue when channel is full and backup the data using `Sender::rx` (Only works with spsc I guess) (Need to validate if the efficiency is much higher this way than other methods). Is this possible?

> There are surely multiple ways to do this

Would love if you can give me some insights :)

**Comment by stjepang** [comment]
> if I can modify `crossbeam-channel`'s internals to point `Receiver::rx` to the tail of internal queue when channel is full and backup the data using `Sender::rx` (Only works with spsc I guess)

Interesting. So it's basically like atomic `.drain()`. This is certainly possible if you're willing to fiddle with the internals of `crossbeam-channel`. You can basically load the head, then the tail and try doing CAS to swing head to the tail and take all elements from the queue. This should also work in MPMC scenarios - I don't see any problem with that.

> Would love if you can give me some insights :)

Here's one quick idea. There'll be some overhead due to locking, but maybe not too bad:

```rust
struct Sender {
    tx: RefCell<Sender<Msg>>,
    rx: Arc<RwLock<Receiver<Msg>>>,
}

struct Receiver {
    rx: Arc<RwLock<Receiver<Msg>>>,
}

impl Sender {
    fn send(&self, msg: Msg) {
        let mut tx = self.tx.borrow_mut();
        select! {
            send(*tx, msg) => {},
            default => {
                let mut rx = self.rx.write();
                let messages = rx.into_iter().collect::<Vec<Msg>>();

                let (tx2, rx2) = channel::bounded(CAP);
                *tx = tx2;
                *rx = rx2;

                drop(rx);
                backup(messages);
            }
        }
    }
}

impl Receiver {
    fn recv(&self) -> Option<Msg> {
        self.rx.read().recv()
    }
}
```

**Comment by tekjar** [comment]
Thanks. I'll try these ideas

**Comment by stjepang** [comment]
Closing the issue. If there's anything else I could help with, do let me know!
