### ISSUE TITLE
Benchmark results for >4 cores

### ISSUE THREAD

**Issue by chisophugis** [crossbeam-rs/crossbeam-channel#69]
I really liked the benchmarks presentation in https://github.com/crossbeam-rs/crossbeam-channel/tree/master/benchmarks

Would it be possible to get those results for >4 cores and threads?

Also, one small suggestion would be to indicate the hardware and OS configuration on which the benchmarks were tested.

**Comment by stjepang** [comment]
I've added machine info to the readme.

Yes, it's not difficult to tweak the tests to use more threads. Every benchmark file has something like this near the top:

```rust
const THREADS: usize = 4;
```

Simply bumping the number up is enough.

Unfortunately, I don't have a machine with more than 4 threads at hand, but you're welcome to play with benchmarks on your machine. Let me know if you get any interesting results. :)

**Comment by ghost** [comment]
Closing the issue since it became stale. If anyone's got benchmark results with higher numbers of threads, let me know.
