### ISSUE TITLE
Microbenchmarks

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#7]
We have a few fun benchmarks against other channels, but for finer performance tuning we'll need those typical `#[bench]` microbenchmarks.

**Comment by PSeitz** [comment]
https://github.com/japaric/criterion.rs is pretty nice for benchmarks

**Comment by ghost** [comment]
Microbenchmarks will be useful for measuring e.g. how long it takes to create a channel and send a single message, but I don't think we'll want to rewrite the current benchmark suite as a set of `#[bench]` benchmarks.
