### ISSUE TITLE
Mac OS supports

### ISSUE THREAD

**Issue by BusyJay** [crossbeam-rs/crossbeam-channel#74]
Does this crate support Mac OS? Several tests fail on Mac OS platform. You can see details [here](https://travis-ci.org/BusyJay/crossbeam-channel/builds/402648574).

**Comment by Terkwood** [comment]
I haven't tried running the tests, but I didn't have any trouble instrumenting a simple application which ran on Mac

**Comment by stjepang** [comment]
I think we just need to bump up durations in tests because `thread:sleep` is less precise on Travis.

**Comment by stjepang** [comment]
I've added Mac OS X to Travis. The tests seem a little bit flaky, but hopefully won't cause problems down the line...
