### ISSUE TITLE
Legible error messages for select_loop! macro

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#8]
We should add additional rules to the macro to pattern-match some common mistakes and then use `compile_error!` to print human-readable messages instead of weird macro errors. Examples of mistakes we should handle:

1. Forgetting parens, e.g. writing `would_block =>` instead of `would_block() =>`.
2. Wrong number of arguments, e.g. writing `recv(rx) =>`.
3. Misspelling a case, e.g. `receive(rx, msg) =>`.

Additionally, it'd be also nice if we could catch duplicate cases. I think that should be doable.

cc @TimNN

**Comment by TimNN** [comment]
#5 already includes on `compile_error!` as an experiment, which has worked great in my small tests.

We should definitely  try to catch common errors, although I think duplicated cases would be difficult (when you say "doable", do you have any specific Idea in mind?)

**Comment by stjepang** [comment]
I'm not completely sure, but with some macro trickery, we could probably at least detect duplicate `disconnected`/`would_block`/`timed_out` declarations.

For example, when expanding `@prelude` perhaps we could keep arguments like `@no_d @no_wb @no_to`.
If we saw a `would_block` case, then we would recursively expand to `@prelude` with arguments `@no_d @yes_wb @no_to`.
Then matching on `@prelude(...) would_block() @_ @yes_wb @_` would result in a `compile_error!`. 
I'm not good with macros, though, so this might be just a naive idea. :)

A more serious problem is that with conditionals we cannot detect duplicate cases anymore. For example, the following macro has no duplicates:

```rust
select_loop! {
    would_block() if 1 + 1 == 2 => {}
    would_block() if 1 + 1 == 3 => {}
}
```

Eh, seems like the problem of duplicate detection is just too difficult to solve at compile time...
