### ISSUE TITLE
How to find out whether a channel is closed?

### ISSUE THREAD

**Issue by bupknar** [crossbeam-rs/crossbeam-channel#83]
Because of the [deprecation of burntsushi's `chan` crate](https://github.com/BurntSushi/chan/), I tried to migrate my code to `crossbeam-channel`, as recommended by burntsushi.  However in some cases I need to distinguish (on the receiver side) between an empty channel and a closed one, which does not seem possible with `crossbeam-channel`.

Luckily for my personal use case, for any channel I either need a receiver that can be cloned (which `crossbeam-channel` provides) _OR_ I need to be able to know whether a channel is closed, but not both at the same time.  So I can use a mixture of `crossbeam-channel` and `std::sync::mpsc` channels in my code and achieve the desired effect.  However it would be really nice if all my channel needs were met by a single implementation.

Is this something that can be emulated by `crossbeam-channel`, or will this be provided in the future?

Other than that, thank you for making this crate! :smile:

**Comment by stjepang** [comment]
You can distinguish between a closed and empty channel using `select!`:

```rust
select! {
    recv(r, msg) => match msg {
        None => println!("closed"),
        Some(m) => println!("received {:?}", m),
    }
    default => println!("empty")
}
```

We should probably document this better.

**Comment by bupknar** [comment]
This is just what I was looking for, thank you! Now I am using crossbeam channels all the way :smile:

Indeed the documentation did not make it clear to me that this was possible.  I previously only glimpsed at the documentation for `select!`, because I did not realize that it allowed me to do more with a channel than just the methods available on the `Receiver`.  I think that putting the example you gave in the `select!` documentation would go a long way to make this clearer.
