### ISSUE TITLE
Importing `select` with 2018 edition

### ISSUE THREAD

**Issue by birkenfeld** [crossbeam-rs/crossbeam-channel#84]
(Caution: I'm not sure if this may be a language issue still in the works.)

When I try to do `use crossbeam_channel::select` to import the macro on Rust 2018, since `select!` uses two helper macros I have to import these as well, ending up with
```
use crossbeam_channel::{select, __crossbeam_channel_parse, __crossbeam_channel_codegen};
```

**Comment by stjepang** [comment]
Yes, this is an annoying one. I can't wait for the new macro system to get over the finish line. :)

For now, I'll just merge the two helper macros with the main one so that we don't have to deal with these kinds of issues.

**Comment by birkenfeld** [comment]
Thanks!
