### ISSUE TITLE
Handling lists of senders/receivers in select_loop!

### ISSUE THREAD

**Issue by stjepang** [crossbeam-rs/crossbeam-channel#9]
Here's a trick that might make the `Select` struct almost completely unnecessary in practice.

In addition to accepting a single receiver `rx` in `recv(rx, msg)`, let's also accept any list of receivers. i.e. anything that implements `IntoIterator<Item = &Receiver<_>>`. The same applies to `send(tx, msg)`. This way `select_loop!` macro could easily handle dynamic cases as well.

An alternative syntax might be `recv(rxs, rx, msg)`, meaning we iterate over the list `rxs`, and when it fires, we get referecen `rx` and message `msg`, meaning `msg` came from `rx`.

For example, I need like to do the following in crate `ipc-channel`. This is currently not possible with `select_loop!` so I have to resort to `Select`.

```rust
select_loop! {
    recv(
        self.receivers
            .iter_mut()
            .map(|r| r.receiver.get_mut().as_ref().unwrap())
            .enumerate(),
        (index, rx) => rx, // This is how we get the receiver from the tuple.
        msg
    ) => {
        println!("Got message from {}-th receiver: {}", index, msg); // We can use the index here.
    }
}
```

By turning the iterator into an enumerating one, we can also get an index of the receiver from which the message was received. I'm not completely sure about the syntax - this is just an idea.

@TimNN, any thoughts on all this?

**Comment by TimNN** [comment]
Thoughts in no particular order:

* I'm in favor of keeping `select_loop!` as simple as possible.
* Adding a new way to pass `tx` / `rx` will add six new variants to the macro
* I would start by prototyping methods like `Select::recv_any<I: IntoIterator<Item=&Receiver>>(...)`
* Do you actually have a use case for getting the index?
* Getting a reference to rx / tx doesn't seem super userful to me, do you have a specific use case?
* If we support getting the index we should more generally support getting a second value, e.g. the key in a HashMap -- that would also support getting the rx / tx if the iterator produced tuples like (rx rx).
* I don't think we can easily support both iterators with index and multiple without index.
* Allowing iterators makes the "same iteration order" guarantee easier to violate.
* I would propose the syntax `recv(any $rx, ...)` for the macro.

The total function signature I envision is something like this:  `fn recv_any<M, I: IntoIterator<Item=(M, &Receiver<T>)>(&mut self, it: I) -> (M, T) { ... }`

**Comment by stjepang** [comment]
> Do you actually have a use case for getting the index?
> Getting a reference to rx / tx doesn't seem super userful to me, do you have a specific use case?

Yes. Sometimes we need to know which channel the message came from. Here's an example:
https://github.com/servo/ipc-channel/blob/master/src/platform/inprocess/mod.rs#L195

I agree that this might complicate the macro too much, though.

**Comment by stjepang** [comment]
This feature seems to be too complicated and I don't think we're going to implement it. Closing.
